modLoader="javafml"
loaderVersion="[47,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/Ivalice/issues"
[[mods]]
modId="ivalice"
version="4.0"
displayName="Ivalice"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ivalice"
logoFile="logo.png"
credits="Thanks to SquareEnix for the Chocobos" #optional
authors="Epidra2077" #optional
description='''
Adds Chocobos to the game
'''
[[dependencies.ivalice]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ivalice]]
    modId="lucky77"
    mandatory=true
    versionRange="[3.0,)"
    ordering="NONE"
    side="BOTH"