modLoader="javafml"
loaderVersion="[38,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/Ivalice/issues"
[[mods]]
modId="ivalice"
version="3.0"
displayName="Ivalice"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ivalice"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Lorem Ipsum
'''
[[dependencies.ivalice]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ivalice]]
    modId="lucky77"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"