modLoader="javafml"
loaderVersion="[35,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/Ivalice/issues"
[[mods]]
modId="ivalice"
version="v03"
displayName="Ivalice"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ivalice"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Lorem Ipsum
'''
[[dependencies.acecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"